---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-privatelink-muziris-template
  title: "Kafka: Create Kafka Private Link in Confluent Cloud for your Subscription"
  annotations:
    mnscorp.net/tutorial-url: "https://confluence.marksandspencer.app/display/CGE/PrivateLink+creation"
  description: "Step-5: To Create Kafka Private Link in Confluent Cloud for your Subscription, use this template."
  tags:
    - kafka
    - confluent
    - confluentcloud
    - topic
    - privatelink
spec:
  owner: events-platform
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - description
        - subscription
        - environment
      properties:
        environment:
          type: string
          title: Name of the Environment for Topic
          ui:autofocus: true
          enumNames:
            - Development
            - Performance
            - Production
          enum:
            - dev
            - perf
            - prod
          default: dev
        subscription:
          title: Subscription Name
          type: object
          ui:field: AzureSubscription
          ui:autofocus: true
          ui:options:
            selector: ['resourceGroup']
          description: Select Azure Subscription Name  to Create Private Link
          
        description:
          title: Description
          type: string
          description: A description for the component

  steps:
    - id: fetch
      name: Template Docs Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          environment: ${{ parameters.environment }}
          description: ${{ parameters.description }}
          subscription: ${{ parameters.subscription }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts: ["github.com"]
        repoUrl: 'github.com?repo=events-platform-resource-selfserve&owner=DigitalInnovation'
        description: 'This is ${{ parameters.environment }}'
        title: 'create-topic-${{ parameters.environment }}-${{ parameters.description }}'
        branchName: 'create-topic-${{ parameters.environment }}-${{ parameters.description }}'
        targetPath: 'muziris-input/topic'  

  output:
    links:
      - title: follow Pull Request.
        url: '${{steps.publish.output.remoteUrl}}'
