apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-topic-muziris-template2
  title: 'Kafka: Create Kafka Topic in Confluent Cloud'
  annotations:
    mnscorp.net/tutorial-url: 'https://confluence.marksandspencer.app/display/CGE/Topic+creation'
  description: 'Step-2: To create a Topic in Confluent Cloud, use this template.'
  tags:
    - kafka
    - confluent
    - confluentcloud
    - topic
spec:
  owner: events-platform
  type: service
  parameters:
    - title: Topic Details
      description: Provide details on Topic
      type: object
      required:
        - env_group
      properties:
        env_group:
          type: object
          title: ''
          required:
            - environment
            - domain
            - team_name
            - async_api_url
            - email_addresses
          properties:
            environment:
              type: string
              title: Name of the Environment for Topic
              'ui:autofocus': true
              enumNames:
                - Development
                - Performance
                - Production
              enum:
                - dev
                - perf
                - prod
              default: dev
            domain:
              type: string
              title: Name of the Domain
              'ui:autofocus': true
              enumNames:
                - Contact
                - Campaign
                - Search & Recommendation
                - Price
                - Stored Value
                - Task
                - Order fulfilment
                - Demand
                - Digital Content
                - Customer Profile
                - Customer Order
                - Payment
                - Stock
                - Transport
                - Product
                - Range
                - Loss prevention
                - Colleague
                - Ledger
                - Identity
                - Location
              enum:
                - Contact
                - Campaign
                - Search & Recommendation
                - Price
                - Stored Value
                - Task
                - Order fulfilment
                - Demand
                - Digital Content
                - Customer Profile
                - Customer Order
                - Payment
                - Stock
                - Transport
                - Product
                - Range
                - Loss prevention
                - Colleague
                - Ledger
                - Identity
                - Location
              default: Contact
            team_name:
              type: string
              title: Name of the team
              description: >-
                Name of the Team. Only alphabets allowed. Maximum 37 characters.
                eg: events
              pattern: '^[a-z]+$'
              'ui:autofocus': true
              maxLength: 37
            topic_category:
              type: string
              title: Category of topic (Public/Private)
              'ui:autofocus': true
              'ui:widget': radio
              enumNames:
                - Public
                - Private
              enum:
                - pub
                - pvt
              default: pub
            dlq:
              type: boolean
              title: Dead Letter Queue(DLQ)
              default: false
            functional_area:
              type: string
              title: Functional Area of the Topic
              description: >-
                Topic Functional Area (Service/Application). Only alphanumeric
                with underscore(_) allowed. Maximum 50 characters. eg:
                pub_events or inbound_service
              'ui:autofocus': true
              pattern: '^[a-z0-9_]+$'
              maxLength: 50
            topic_description:
              type: string
              title: Description for Topic
              description: >-
                Topic Description. Only alphanumeric with underscore(_) allowed.
                Maximum 70 characters. eg: click_info
              pattern: '^[a-z0-9_]+$'
              'ui:autofocus': true
              maxLength: 70
          dependencies:
            environment:
              oneOf:
                - properties:
                    environment:
                      enum:
                        - dev
                    partitions:
                      type: integer
                      title: Number of partition of the topic
                      description: Number of partition of the topic. Maximum 1 partition
                      'ui:autofocus': true
                      default: 1
                      minimum: 1
                      maximum: 1
                    retention_time:
                      type: integer
                      title: Retention Time
                      'ui:autofocus': true
                      enumNames:
                        - 1 hour
                        - 1 day
                        - 1 week
                      enum:
                        - 3600000
                        - 86400000
                        - 604800000
                      default: 604800000
                    retention_size:
                      type: integer
                      title: Retention Size
                      'ui:autofocus': true
                      enumNames:
                        - 1 MB
                        - 100 MB
                        - 500 MB
                        - 1 GB
                        - 1 TB
                      enum:
                        - 1048576
                        - 104857600
                        - 524288000
                        - 1073741824
                        - 1099511627776
                      default: 524288000
                    message_max_size:
                      type: integer
                      title: Message Maximum size in bytes
                      description: >-
                        Message Maximum size in bytes. Should be <= 20971520
                        (20MB) 
                      'ui:autofocus': true
                      default: 2097164
                      maximum: 20971520
                    cleanup_policy:
                      type: string
                      title: Topic Cleanup policy
                      'ui:autofocus': true
                      enumNames:
                        - Delete
                        - Compact
                      enum:
                        - delete
                        - compact
                      default: delete
                    async_api_url:
                      type: string
                      title: Async API Url
                      description: >-
                        Async API URL. eg:
                        https://github.com/DigitalInnovation/events-platform-asyncapi/blob/main/asyncapis/ct-chbr-stepbrandsproductservice/asyncapi.yaml
                      format: url
                      'ui:autofocus': true
                    email_addresses:
                      type: string
                      title: Email Addresses of team
                      description: >-
                        Email Addresses of the Team. Email addresses should be
                        ending with mnscorp.net and multiple emails should be
                        separated by (;). eg:
                        john.smith@mnscorp.net;tony.blaze@mnscorp.net
                      format: text
                      pattern: '^(([A-Za-z0-9._%+-]+@[mnscorp]+\.[net]{2,4}(;|$)\s?))*$'
                      'ui:autofocus': true
                      maxLength: 500
                - properties:
                    environment:
                      enum:
                        - perf
                    partitions:
                      type: integer
                      title: Number of parition of the topic
                      description: Number of partition of the topic. Maximum 6 partitions
                      'ui:autofocus': true
                      default: 1
                      minimum: 1
                      maximum: 6
                    retention_time:
                      type: integer
                      title: Retention Time (Don't choose Infinite unless necessary)
                      'ui:autofocus': true
                      enumNames:
                        - 1 hour
                        - 1 day
                        - 1 week
                        - 1 month
                        - 1 year
                        - infinite
                      enum:
                        - 3600000
                        - 86400000
                        - 604800000
                        - 2592000000
                        - 31536000000
                        - -1
                      default: -1
                    retention_size:
                      type: integer
                      title: Retention Size (Don't choose Infinite unless necessary)
                      'ui:autofocus': true
                      enumNames:
                        - 1 MB
                        - 100 MB
                        - 500 MB
                        - 1 GB
                        - 1 TB
                        - infinite
                      enum:
                        - 1048576
                        - 104857600
                        - 524288000
                        - 1073741824
                        - 1099511627776
                        - -1
                      default: 524288000
                    message_max_size:
                      type: integer
                      title: Message Maximum size in bytes
                      description: >-
                        Message Maximum size in bytes. Should be <= 8388608
                        (8MB) 
                      'ui:autofocus': true
                      default: 2097164
                      maximum: 8388608
                    cleanup_policy:
                      type: string
                      title: Topic Cleanup policy
                      'ui:autofocus': true
                      enumNames:
                        - Delete
                        - Compact
                      enum:
                        - delete
                        - compact
                      default: delete
                    async_api_url:
                      type: string
                      title: Async API Url
                      description: >-
                        Async API URL. eg:
                        https://github.com/DigitalInnovation/events-platform-asyncapi/blob/main/asyncapis/ct-chbr-stepbrandsproductservice/asyncapi.yaml
                      format: url
                      'ui:autofocus': true
                    email_addresses:
                      type: string
                      title: Email Addresses of team
                      description: >-
                        Email Addresses of the Team. Email addresses should be
                        ending with mnscorp.net and multiple emails should be
                        separated by (;). eg:
                        john.smith@mnscorp.net;tony.blaze@mnscorp.net
                      format: text
                      pattern: '^(([A-Za-z0-9._%+-]+@[mnscorp]+\.[net]{2,4}(;|$)\s?))*$'
                      'ui:autofocus': true
                      maxLength: 500
                - properties:
                    environment:
                      enum:
                        - prod
                    partitions:
                      type: integer
                      title: Number of parition of the topic
                      description: Number of partition of the topic. Maximum 6 partitions
                      'ui:autofocus': true
                      default: 1
                      minimum: 1
                      maximum: 6
                    retention_time:
                      type: integer
                      title: Retention Time (Don't choose Infinite unless necessary)
                      'ui:autofocus': true
                      enumNames:
                        - 1 hour
                        - 1 day
                        - 1 week
                        - 1 month
                        - 1 year
                        - infinite
                      enum:
                        - 3600000
                        - 86400000
                        - 604800000
                        - 2592000000
                        - 31536000000
                        - -1
                      default: -1
                    retention_size:
                      type: integer
                      title: Retention Size (Don't choose Infinite unless necessary)
                      'ui:autofocus': true
                      enumNames:
                        - 1 MB
                        - 100 MB
                        - 500 MB
                        - 1 GB
                        - 1 TB
                        - infinite
                      enum:
                        - 1048576
                        - 104857600
                        - 524288000
                        - 1073741824
                        - 1099511627776
                        - -1
                      default: 524288000
                    message_max_size:
                      type: integer
                      title: Message Maximum size in bytes
                      description: >-
                        Message Maximum size in bytes. Should be <= 20971520
                        (20MB) 
                      'ui:autofocus': true
                      default: 2097164
                      maximum: 20971520
                    cleanup_policy:
                      type: string
                      title: Topic Cleanup policy
                      'ui:autofocus': true
                      enumNames:
                        - Delete
                        - Compact
                      enum:
                        - delete
                        - compact
                      default: delete
                    async_api_url:
                      type: string
                      title: Async API Url
                      description: >-
                        Async API URL. eg:
                        https://github.com/DigitalInnovation/events-platform-asyncapi/blob/main/asyncapis/ct-chbr-stepbrandsproductservice/asyncapi.yaml
                      format: url
                      'ui:autofocus': true
                    email_addresses:
                      type: string
                      title: Email Addresses of team
                      description: >-
                        Email Addresses of the Team. Email addresses should be
                        ending with mnscorp.net and multiple emails should be
                        separated by (;). eg:
                        john.smith@mnscorp.net;tony.blaze@mnscorp.net
                      format: text
                      pattern: '^(([A-Za-z0-9._%+-]+@[mnscorp]+\.[net]{2,4}(;|$)\s?))*$'
                      'ui:autofocus': true
                      maxLength: 500
  steps:
    - id: fetchBase
      name: Fetch Base
      action: 'fetch:template'
      input:
        url: ./template
        values:
          name: '${{parameters.application_name}}'
          destination: >- test
        gitAuthorName: '${{ user.entity.metadata.name }}'
        gitAuthorEmail: '${{ user.entity.spec.profile.email }}'
  output:
    links:
      - title: Follow link to Github repo and Pull request for next steps
        url: '${{steps.publish.output.remoteUrl}}'
