apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: m1
  title: 'Kafka: Create Kafka Topic in Confluent Cloud'
  annotations:
    mnscorp.net/tutorial-url: 'https://confluence.marksandspencer.app/display/CGE/Topic+creation'
  description: 'Step-2: To create a Topic in Confluent Cloud, use this template.'
  tags:
    - kafka
spec:
  owner: integration-frameworks
  type: service
  parameters:
    - title: Self service template for Resource Group Access
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          pattern: ^[a-z,0-9]{1,8}$
          ui:autofocus: true
          ui:options:
            rows: 5
        team:
          type: string
          description: Unique name of the component
          pattern: ^[a-z,0-9]{1,8}$
          ui:autofocus: true
          ui:options:
            rows: 5
